### ISSUE TITLE
Best Practice Checklist

### ISSUE THREAD

**Issue by expede** [fission-suite/ipfs-user-settings#2]
* GitHub
  * [x] Tags
  * [ ] Project Link (often a live demo)
* README
  * [ ] Description
  * [ ] Quickstart
  * [ ] Image
  * [ ] Link to live demo
  * [ ] Link to NPM
  * [ ] Badges (NPM, CI, &c)
* Checks
  * [ ] Set up on TravisCI
  * [ ] Set up on CodeClimate
